openapi: 3.0.2
info:
  title: OpenWeatherMap API
  description:
    $ref: description.md

  version: '2.5'
  termsOfService: 'https://openweathermap.org/terms'
  contact:
    name: OpenWeatherMap API
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
paths:
  /weather:
    $ref: paths\weather.yaml
security:
  - app_id: []
tags:
  - name: Current Weather Data
    description: Get current weather details
externalDocs:
  description: API Documentation
  url: 'https://openweathermap.org/api'
components:
  securitySchemes:
    app_id:
      type: apiKey
      description: >-
        API key to authorize requests. (If you don't have an API key, get one at
        https://openweathermap.org/. See
        https://idratherbewriting.com/learnapidoc/docapis_get_auth_keys.html for
        details.)
      name: appid
      in: query
